apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: my-spring-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_CONFIG_LOCATION
              value: /config/

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: GEMINI_API_KEY

            - name: WHATSAPP_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: WHATSAPP_ACCESS_TOKEN

          volumeMounts:
            - name: config-volume
              mountPath: /config

      volumes:
        - name: config-volume
          configMap:
            name: spring-config